
/*Created by Omri Kaisari on 07/08/2020.*/

enum errorType {
    COMMAND_NOT_FOUND,
    TOO_MANY_OPERANDS,
    TOO_FEW_OPERANDS,
    DIRECTIVE_NOT_FOUND,
    ILLEGAL_LABEL
};


#ifndef ASSEMBLER_ERRORS_H
#define ASSEMBLER_ERRORS_H

#endif /*ASSEMBLER_ERRORS_H*/
